py-scripts/examples/port_probe.py, py-scripts/examples/radio_info.py, py-scripts/examples/show_ports.py
Include `py-scripts/examples/` scripts in automated linting, first fixing linting failures in `show_ports.py` script.
=> Include py-scripts/examples/ Scripts in Automated Linting

lf_gui_cmd.pl
In recent LANforge versions, the 'Auto Save Report' checkbox ('auto_save' key in config) has been added to the default saved config values. Thus, using the 'cv click' GUI cmd will toggle this, when really a user just wants it always enabled.
This change ensures the 'Auto Save Report' option is always enabled.
Verified:
./lf_gui_cmd.pl \
--mgr       192.168.91.50 \
--port      3990 \
--ttype     "WiFi Capacity" \
--rpt_dest  "/var/www/html/lf_reports"
=> lf_gui_cmd.pl: Fix auto save not selected regression

.github/workflows/ci.yml
Addresses recent change of 'ubuntu-latest' runner
bumped to Ubuntu 24.04 LTS. More details here:
https://github.com/actions/runner-images/issues/10636
This fixes Python 3.7 issue in linting action.
=> ci: Set runner version to Ubuntu 22.04 LTS

py-scripts/lf_atten_mod_test.py
py-scripts/lf_atten_mod_test.py only needed the arguments in the
Realm.create_bare_argparse to remove the CX and radio related arguments that are not needed.
Verified:
./lf_atten_mod_test.py --help
=> py-scripts/lf_atten_mod_test.py : to use create_bare_argparse elimnates unnessary args like CX and Radio

py-scripts/test_l3.py
This commit is to make some of the examples executable when copied without editing
Verified:
--no_cleanup\
--cleanup_cx
=> py-scripts/test_l3.py updated two examples to be executible when copied

py-scripts/test_l3.py
Updated the test_l3.py to have --dowebgui switch to use action='store_true' in effort to pass flake8
Verified:
--no_cleanup\
--cleanup_cx
=> py-scripts/test_l3.py have --dowebgui use action='store_true'

py-scripts/test_l3.py
Commented out unused variables left in as reference
Verified:
--no_cleanup\
--cleanup_cx
=> py-scripts/test_l3.py LAN-3596 flake8: commented out unused variables

py-scripts/test_l3.py
py-scripts/test_l3.py LAN-3596 flake8: removed import of pprint unused
flake8 complience removed import of pprint
Verified:
--no_cleanup\
--cleanup_cx
Signed-off-by: Chuck SmileyRekiere <chuck.smileyrekiere@candelatech.com>
=> Test l3 flake8 removed import of pprint unused     , corrected long lines

py-scripts/test_l3.py
flake8 compliance: the long return lists moved to multiple lines to allow flake8 to pass
Verified:
--no_cleanup\
--cleanup_cx
=> py-scripts/test_l3.py flake8 compliance: long line returns shortened

py-scripts/test_l3.py
flake8 compliance: long line returns shortened , commented out import of traceback , put in TODO
for if there exceptions put in will have traceback in place
Verified:
--no_cleanup\
--cleanup_cx
Signed-off-by: Chuck …
=> Test l3 flake8 compliance:  long line returns shortened one commit , other commit  commented out import of traceback

py-scripts/test_l3.py
flake8 compliance ,  dl_rx_drop_percent possibly mis-labeled ast it was reading rx drop this was caught by flake8
Verified:
--no_cleanup\
--cleanup_cx
=> test_l3.py LAN-3133 flake8 compliance: dl_rx_drop_percent updated

py-scripts/test_l3_longevity.py
test_l3_longevity.py LAN-3597 flake8 compliant
--no_cleanup\
--cleanup_cx
=> test_l3_longevity.py LAN-3597 flake8 compliant fixed logger.debug

py-scripts/lf_base_interop_profile.py
Updates to lf_base_interop_profile.py in preperation for flake8
multiple commits to prepare lf_base_interop_profile.py in preperation for flake8 
The base class was verified with 
./lf_interop_ping.py --mgr 192.168.50.103  --target 192.168.50.203 --virtual --num_sta 1 --radio 1.1.wiphy2 --ssid ax88u_5g --security wpa2 \
--passwd lf_ax88u_5g --ping_interval 1 --ping_duration .2 --server_ip 192.168.50.1 --debug --local_lf_report_dir /home/lanforge/html-results
=> Updates to lf_base_interop_profile.py in preperation for flake8

lanforge_client/examples/query_metrics/query_metrics.py, py-scripts/lf_rvr_test.py, py-scripts/lf_tr398_test.py
This commit series addresses `flake8-bugbear` highlighted code error/warning feedback in all currently-linted scripts, save `test_l3.py`. These commits prepare the repository for potential addition of `flake8-bugbear`-based checks in linting CI workflow.
=> Address Bugbear Linting Feedback

py-scripts/lf_create_wanlink.py
Corrected issue where wanlink endpoints fields were reflected (ie Drop-freq for A would be populated for B and vice versa). 
Added lf_create_wanpath to create a wanpath using the lanforge api given an existing wanlink endpoint - based off of lf_create_wanlink.
=> lf_create_wanlink.py: LAN-3445 - _tx_endp assigned corrected

py-json/LANforge/lfcli_base.py, py-json/cv_test_manager.py
Mostly readability/quality of life patches, including setting `dest` for multi-option arguments. Also fixed an issue related to KPI file checks when no `--pull_report` or `--lf_local_report_dir` is specified.
See the final commit in the series for the verification CLI (using WCT).
=> Updates to py-json Chamber View test automation core logic

.gitignore, CONTRIBUTING.md, README.md, archive/README.md, lanforge_client/README.md, py-json/README.md, py-scripts/README.md, py-scripts/cv_examples/README.md, py-scripts/sandbox/README.md
General documentation cleanup, primarily by running prettier formatter on Markdown documentation. Additionally updated gitignore to use a standard Python gitignore provided by GitHub (link [here](https://github.com/github/gitignore/blob/ceea7cab239eece5cb9fd9416e433a9497c2d747/Python.gitignore)).
=> Cleanup docs, update gitignore

py-scripts/lf_create_wanlink.py
py-scripts/lf_create_wanlink.py flake 8 compliance,  white space , exceptions , linting exceptions for imports and line length
Verified:
./lf_create_wanlink.py\
--mgr 192.168.50.104\
--mgr_port 8080\
--port_A eth1\
--port_B eth3\
--speed_A 1024000\
--speed_B 2048000\
--wl_name wanlink\
--latency_A 24\
--latency_B 32\
--max_jitter 50\
--jitter_freq 6\
--drop_freq 12\
--log_level debug\
--debug
=> flake8 compliance lf_create_wanlink.py 

py-scripts/lf_create_vap_cv.py, py-scripts/lf_create_wanlink.py
lf_create_vap_cv.py  flake8 remove white space
Verified:
./lf_create_vap_cv.py\
--mgr 192.168.50.104\
--port 8080\
--lf_user lanforge\
--lf_password lanforge\
--delete_old_scenario\
--scenario_name dfs_2\
--vap_radio wiphy1\
--vap_freq 5700\
--vap_ssid mtk7915_5g_b\
--vap_passwd lf_mtk7915_5g_b\
--vap_security wpa2\
--vap_bw 20\
--vap_upstream_port 1.1.eth1
=> lf_create_vap_cv.py  flake8 remove white space

py-scripts/lf_create_vap_cv.py
lf_create_vap_cv.py  flake 8 linting 
removed unused packages and removed the # flake8: noqa
Verfied:
./lf_create_vap_cv.py\
--mgr 192.168.50.104\
--port 8080\
--lf_user lanforge\
--lf_password lanforge\
--delete_old_scenario\
--scenario_name dfs_2\
--vap_radio wiphy1\
--vap_freq 5700\
--vap_ssid mtk7915_5g_b\
--vap_passwd lf_mtk7915_5g_b\
--vap_security wpa2\
--vap_bw 20\
--vap_upstream_port 1.1.eth1
=> lf_create_vap_cv.py  flake 8 linting 

py-scripts/lf_create_wanpath.py
Check that reserved ports (ie 4001 and 4002) are not used as mgr. Request alternative if attempted.
Verified with:
./lf_create_wanpath.py --mgr 192.168.101.189 --mgr_port 4001\
--wp_name test_wp-B --wl_endp test_wl-B\
--log_level debug --debug
./lf_create_wanpath.py --mgr 192.168.101.189 --mgr_port 4002\
--wp_name test_wp-B --wl_endp test_wl-B\
--log_level debug --debug
=> lf_create_wanpath.py: LAN-1963 - added port verification logic

py-scripts/lf_create_wanpath.py
Updated arg parsing/verification to be stand-alone functions outside of main. 
Added support for --help_summary flag per LAN-3133. 
Signed-off-by: Cameron LaPlante <Cameron.laplante@candelatech.com>
=> lf_create-wanpath.py: LAN-3133 - Updated arg parsing and added --help_summary support

.pre-commit-config.yaml
This PR updates pre-commit to the latest version in addition of a shebang and shell linting checks.
The shebang check is simple and does a common sense check. The shell linting check maybe not so much.
Inspiration for this series comes from the [linux-firmware](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/.pre-commit-config.yaml) repository's pre-commit config. It includes several more checks than we do here (like the opinionated Python formatter `black`), some of which I feel are appropriate to introduce.
@memnochproxy do you mind reviewing this as well? Given that primarily you and @smileyrekiere develop the newer Bash scripts in this repository, I want to make sure you're on board with this before we introduce it. I don't know that you …
=> Updates to pre-commit configuration

py-scripts/test_l3.py
More cleanup/refactoring for `test_l3.py`. Time permitting, I intend to submit a few more patch series for this script.
There's some churn here, so please keep an eye for regressions. I moved some WebGUI code to a helper in one of the commits, but that change seemed pretty low risk comparatively.
Series rebased on current master (includes other `test_l3.py` changes) is tested with the following CLI, as detailed in the final commit in the series:
```Bash
Verified:
./test_l3.py \
--test_duration    1m \
--endp_type        mc_udp \
--download_min_bps 1000000 \
--upstream_port    1.3.eth2 \
--radio "radio==1.1.wiphy0,stations==5,ssid==Mesh,ssid_pw==lanforge,security==wpa2"
./test_l3.py \
--test_duration     1m \
--endp_type         lf_udp \
--download_min_bps  1000000 \
--upstream_port …
```
=> Cleanup/refactoring for 'test_l3.py'

.github/workflows/ci.yml, py-scripts/lf_help_check.bash, py-scripts/tools/lf_help_check.py
In line with performing more sanity checks using available GitHub Actions-based automation, this patch series implements a new GitHub Actions-based help check using a new Python help check script.
This PR updates the existing CI action to run the help check in parallel with the existing linting check, minimizing delay in action results. Additionally, the new Python script is designed to run help checks in parallel, speeding up the process and reducing the number of GitHub runner minutes utilized. Additional fixes are added to the existing Bash help check script to exit on failure if any of the scripts fail, rather than only logging the failures.
I intend to update the Python script to support checking help summaries as well, but I have not yet implemented that.
=> Add GitHub Actions-based Help Check

py-scripts/lf_ftp.py
- Added support for configuring devices listed in device_list with SSID,password, and security
- Added support for configuring devices in group with specific profiles
- Added ability to set device-specific or common pass/fail values for all devices 
Verified CLI:
python3 lf_ftp.py --file_sizes 1MB --mgr 192.168.204.74 --traffic_duration 1m  --directions Download --clients_type Real  --bands 5G --upstream_port eth1 --ssid NETGEAR_5G_wpa2 --passwd Password@123 --security wpa2 --config
=> lf_ftp.py: Add device configuration and pass/fail validation support

py-scripts/lf_interop_ping_plotter.py
- Added support for configuring devices listed in device_list with SSID,password, and security
- Added support for configuring devices in group with specific profiles
- Added ability to set device-specific or common pass/fail values for all devices
Verified CLI:
python3 lf_interop_ping_plotter.py --mgr 192.168.204.74 --real --target 192.168.204.66 --ping_interval 1 --ping_duration 1m  --ssid NETGEAR_2G_wpa2     --security wpa2 --passwd Password@123 --server_ip 192.168.204.74 --wait_time 30
=> lf_interop_ping_plotter.py: Add device config and pass/fail validation

py-scripts/lf_cleanup.py, py-scripts/lf_client_visualization.py, py-scripts/lf_create_vap_cv.py, py-scripts/lf_create_wanlink.py, py-scripts/test_l3.py, py-scripts/tools/lf_cli_to_testjson.py
This series fixes (and in some cases ignores) linting failures flagged by flake8-bugbear for all scripts except those involved in interop and WebUI (will address those after current PRs are merged). **This does NOT add flake8-bugbear to linting**.
=> Address linting failures flagged by flake8-bugbear

py-scripts/test_l3.py
This commit updates the comments to show how to configure the wifi 7 and updated checking to allow wifi 7
abgn7       | 16        #  802.11abgn-EHT
bgn7        | 17        #  802.11bgn-EHT
an7         | 18        #  802.11an-EHT
a7          | 19        #  802.11a-EHT (6E disables /n and /ac)
also updated was the comments with examples
=> Test l3 lan-4069 Wifi 7 updates and examples

py-scripts/lf_interop_video_streaming.py
lf_interop_video_streaming.py: enhance CLI, config mode, group-profile mapping, and pass/fail logic
- Added support for configuring devices via command-line using --config, --ssid, --passwd, --encryp, and --upstream_port
- Implemented group-to-profile mapping with --group_name, --profile_name, and --file_name arguments
- Enabled pass/fail logic with --expected_passfail_value and --device_csv_name using actual vs expected URL count
- Added change_port_to_ip() to dynamically resolve upstream ports into IP addresses
- Implemented update_webui_json() and updating_webui_runningjson() to sync test progress with Web UI
- Introduced filter_ios_devices() to exclude iOS devices based on hardware identifiers
- Enhanced report generation with pass/fail status and expected URL comparison
- Removed …
=> lf_interop_video_streaming.py: enhance CLI, config mode, group-profile mapping, and pass/fail logic

py-scripts/lf_create_vap_cv.py
LAN-4089 : Customer Request: Comcast-India customer ./lf_create_vap_cv.py script requirement
This Jira is to add the ability to pass in a channel when creating a vap. Verified:
./lf_create_vap_cv.py\
--mgr 192.168.101.137\
--port 8080\
--lf_user lanforge\
--lf_password lanforge\
--delete_old_scenario\
--scenario_name at7_vap_chan\
--vap_radio 1.2.wiphy2\
--vap_channel 1e\
--vap_ssid at7_6g\
--vap_passwd hello123\
--vap_security wpa3\
--vap_bw 320\
--vap_upstream_port 1.1.eth2
=> LAN 4089 vap chan: Customer Request: Comcast-India customer ./lf_create_vap_cv.py script requirement

py-scripts/lf_interop_qos.py
- Waits up to 20 retries for all CXs (connections) to be created
- Devices will be excluded from the test if their cross-connections are not created.
=> lf_interop_qos.py: Add monitor_cx to wait for CX creation

py-scripts/lf_interop_throughput.py
Previously, when calculating averages from the dataframe/CSV in script, we excluded the first and last records in the CSV file because they were considered redundant.
Following recent discussions in JIRA WC-1355, we now modified the logic to excluded the first and last records directly in csv itself.
=> lf_interop_throughput.py: WC-1355 – Trimmed redundant columns in CSV

py-scripts/lf_interop_ping_plotter.py
- Added logic to handle connectivity checks when tests are triggered from the WebGUI Verified CLI: python3 lf_interop_ping_plotter.py --mgr 192.168.244.97 --real --target 8.8.8.8 --ping_interval 1 --ping_duration 1m --ssid xiab_2G_WPA2 --security wpa2 --passwd lanforge --server_ip 192.168.1.14 --wait_time 30
=> lf_interop_ping_plotter: Handle connectivity for WebGUI tests

.flake8, .github/workflows/ci.yml, .pre-commit-config.yaml
More details provided in internal chat, but this introduces use of `flake8-bugbear` plugin for more aggressive linting both in GitHub Actions linting workflow as well as in the `pre-commit` configuration.
This presently will ignore specific errors in files which fail, while still linting the rest of the file. Goal is to slowly fix these as we work on them going forward.
=> Add bugbear linting, ignore failing file errors for now

py-scripts/temp_graph.py
Temp_graph is a small script that parses the output from _journalctl -t heatmon_ into a series of CSVs (separated by timeframe and device type (radio/core)). It then can produce a report page with a series of graphs for each of these tables. This makes it easier to visually report temperature stats when testing systems. I originally wrote this script independently a few months before coming to CT, but have rewritten most of it in the last week to be more useful and visually appealing.
Design Notes:
-This script uses the matplotlib library to create its graphs. This library is used in other places in the lanforge codebase, but may not be the most robust option in the long run.
-The regex used to parse lines from _journalctl -t heatmon_ is pretty specific and will break (but will be easy to …
=> Add temp_graph.py to py-scripts

py-scripts/tools/lf_update.py
updated to pass in the timeouts and suggested timeouts based on the lANforge type
Verified:
// ./lf_update.py 523c
"args":[
"--mgr", "192.168.50.104",
"--root_user", "root",
"--root_password", "lanforge",
"--user", "lanforge",
"--user_password", "lanforge",
"--mgr_ssh_port", "22",
"--log_level","info",
"--lfver","5.5.1",
"--kver","6.15.6+",
"--user_timeout","10",
"--root_timeout","300",
"--log_level","info"
]
=> py-scripts/tools/lf_update.py

py-scripts/real_application_tests/youtube/lf_interop_youtube.py
Previously, the script sorted rows by TimeStamp after removing duplicates.
This caused issues for tests crossing midnight (e.g., 23:49 → 01:39), where
times from the next day could appear before late-night values. Since the CSV
already logs data in order, sorting is unnecessary. The plot now preserves
the original logging order."
=> lf_interop_youtube.py: remove unnecessary TimeStamp sorting
