py-scripts/lf_report.py
py-scripts/lf_we_can_scan.py
py-scripts/lf_we_can_wifi_capacity.py

Signed-off-by: amrit <amrit.raj@candelatech.com>
Added we-can scan script which scans specified ssid on all the real-clients (Phones) and generate a report for it and added some add-on features to lf_report.py

lf_report.py:  modified headers of scripts properly in specified format

---

py-scripts/lf_we_can_scan.py

as requested by QA team to change the objective in the scan test report

---

py-scripts/lf_we_can_scan.py

WC-370
Signed-off-by: amrit <amrit.raj@candelatech.com>

lf_we_can_scan.py: Added div break in reporting

---

py-scripts/lf_report.py
py-scripts/lf_we_can_wifi_capacity.py

lf_we_can_wifi_capacity: Added wifi-capacity for WE-CAN real clients along with reporting

---

py-scripts/lf_we_can_wifi_capacity.py

Signed-off-by: amrit <amrit.raj@candelatech.com>

removed average of Rx and Tx speed

---

py-scripts/lf_interop_installer.py
py-scripts/lf_interop_rvr_test.py
py-scripts/lf_we_can_wifi_capacity.py

added a script which will install apk to the phones which are connected to lanforge using usb cable

Wc 424 lanforge interop app installer script

---

py-scripts/lf_report.py
py-scripts/lf_we_can_wifi_capacity.py

Modified Wi-Fi Capacity report

Wc 413: Modified Wi-Fi Capacity report

---

py-scripts/lf_report.py
py-scripts/lf_we_can_wifi_capacity.py

WC-413: Updated wifi capacity test report

WC-413: Updated wifi capacity test report

---

py-scripts/lf_interop_rvr_test.py

lf_interop_rvr_test.py: updated the report according to PM team requirements

lf_interop_rvr_test.py: updated the report according to PM team requirements

---

py-scripts/lf_interop_rvr_test.py

Reverts greearb/lanforge-scripts#21

Revert "lf_interop_rvr_test.py: updated the report according to PM team requirements"

---

py-scripts/examples/testbed_health_check.py

Script directly invokes the LANforge JSON API to simplify workflow for end users.

Add Example Script to Query LANforge Testbed Status

---

lanforge_client/__init__.py
lanforge_client/examples/query_all_ports.py
lanforge_client/examples/query_json_endpoint.py
lanforge_client/examples/query_specific_port.py
lanforge_client/examples/query_vap_stations.py
lanforge_client/examples/visualize_latency.py
py-scripts/__init__.py
py-scripts/create_bridge.py
py-scripts/create_macvlan.py
py-scripts/create_qvlan.py
py-scripts/create_station.py
py-scripts/examples/port_probe.py
py-scripts/examples/radio_info.py
py-scripts/examples/show_ports.py
py-scripts/examples/testbed_health_check.py
py-scripts/sandbox/__init__.py

These updates primarily involve adding or refactoring docstrings to meet Google standards, as agreed upon by our scripting development team.

Update Scripts to Address Linting Feedback

---

py-scripts/sandbox/cc_module_plumeos.py

Example PR for demonstration purposes

Fix lint check failure, whitespace format sandbox script

---

py-scripts/lf_base_interop_profile.py
py-scripts/lf_interop_ping.py

This pull requests contain a series of commits for flake8 for lf_interop_ping.py ,
Verified:
Verified:
./lf_interop_ping.py\
--mgr 192.168.50.103\
--target 192.168.50.203\
--virtual\
--num_sta 1\
--radio 1.1.wiphy2\
--ssid ax88u_5g\
--security wpa2\
--passwd lf_ax88u_5g\
--ping_interval 1\
--ping_duration .2\
--server_ip 192.168.50.1\
--debug\
--local_lf_report_dir /home/lanforge/html-results

lf_interop_ping.py edits for enabling flake8

---

py-scripts/lf_ap_auto_test.py

Pull Reqest to have lf_ap_auto_test.py to be flake8 complient

Pull Reqest to have lf_ap_auto_test.py to be flake8 complient

---

py-scripts/create_chamberview_dut.py

./create_chamberview_dut.py  flake8 cleanup
Verified:
./create_chamberview_dut.py  --lfmgr 192.168.50.104 --port 8080 --dut_name ax88u --ssid 'ssid_idx=0 ssid=ax88u_2g security=wpa2 password=lf_ax88u_2g bssid=f0:2f:74:c7:a2:00' --ssid 'ssid_idx=1 ssid=ax88u_5g security=wpa2 password=lf_ax88u_5g bssid=f0:2f:74:c7:a2:04' --sw_version sw_ver_1.1 --hw_version hw_ver_1.1 --serial_num DUT_SERIAL --model_num ax88u

./create_chamberview_dut.py  flake8 cleanup

---

py-scripts/create_chamberview.py

create_chamberview.py flake8 cleanup removed white space and then # flake8: noqa
Verified:
./create_chamberview.py  --lfmgr 192.168.50.104 --port 8080 --delete_scenario --create_scenario ap_auto --raw_line "profile_link 1.1 STA-AUTO 4 'DUT: ax88u Radio-1' NA AUTO,AUTO -1 NA"  --raw_line "profile_link 1.1 STA-AUTO 4 'DUT: ax88u Radio-2' NA AUTO,AUTO -1 NA"  --raw_line "profile_link 1.1 upstream-dhcp 1 NA NA eth2,AUTO -1 NA "

create_chamberview.py flake8 cleanup

---

py-scripts/tools/lf_test_gen/lf_create_ap_auto_json.py
py-scripts/tools/lf_test_gen/lf_create_ap_auto_tab.py

Updates to AP auto test generation WIP 
./lf_test_gen.py --radio_count 8

Updates to AP auto test generation WIP

---

py-scripts/examples/show_mlo_links.py

This script is for testing the HttpMlo.java handler.
Verified with:
./show_mlo_links.py --mgr 192.168.101.189 --addtl_fields "noise,activity"

show_mlo_links.py: initial commit

---

py-scripts/cv_manager.py
py-scripts/lf_client_visualization.py
py-scripts/lf_interference.py
py-scripts/lf_modify_radio.py
py-scripts/lf_report.py

Mostly white space changes to move toward consistent flake8 compliance across python scripts.

Updated flake8 compliance on several scripts

---

py-scripts/lf_base_interop_profile.py
py-scripts/test_l3.py

General scripts cleanup, primarily focused on `test_l3.py`. Includes logging, whitespace, commenting, and moving items to helper functions
CC: @goyalsaurabh06 @akhilesh1201

Script cleanup, primarily 'test_l3.py'

---

py-json/cv_test_manager.py

Verified:
./lf_wifi_capacity_test.py \
--num_stations  1 \
--download_rate 1Mbps \
--upload_rate   1Kbps \
--stations      1.1.sta0000 \
--upstream      1.1.eth2

cv_test_manager.py: Fix test creation error check

---

py-json/interop_connectivity.py
py-scripts/DeviceConfig.py
py-scripts/lf_base_interop_profile.py

Added CLI help for groups and profiles creation in DeviceConfig.py, enhanced profile parsing to skip passwords for open encryption, and improved CLI descriptions and flag support. Updated lf_base_interop_profile.py to include enterprise parameters in the configure_wifi_groups function. Modified interop_connectivity.py to add enterprise parameters with default values in the set_encoding function.

Device config

---

py-scripts/test_l3.py

Station profiles do not generate their station names until during creation. Thus, querying the station names before creation resulted in no stations waited on for connectivity cascading into CXs not starting.
Verified:
./test_l3.py \
--upstream_port    1.1.eth2 \
--endp_type        lf_udp \
--rates_are_totals \
--side_a_min_bps   20000 \
--side_b_min_bps   300000000 \
--radio 'radio==wiphy1,stations==4,ssid==ASUS_2C_5G-1,ssid_pw==hello123,security==wpa2'
./test_l3.py \
--test_duration             1m \
--endp_type                 lf_udp \
--download_min_bps          1000000 \
--upstream_port             1.3.eth2 \
--use_existing_station_list \
--existing_station_list     1.1.sta0000

test_l3.py: Fix regression causing CXs to not start

---

py-json/port_probe.py
py-scripts/examples/port_probe.py

Commenting, whitespace/readability, and inclusion of py-json port probe script in linting.

Minor Updates to Port Probe scripts

---

py-json/cv_test_manager.py
py-scripts/lf_dataplane_test.py

Cleanup to Dataplane script and new CLI options (forthcoming in patches I'll post to this branch soon)

Updates/cleanup to Dataplane test script

---

py-scripts/tools/lf_help_check.py

Adds about 30 seconds to each workflow run.

tools/lf_help_check.py: Add help summary check

---

py-scripts/lf_dataplane_test.py

Fixes recently introduced linting failure, adds support for attenuator configuration in CLI (directly but still supported by rawlines), and updates header/help to include more examples.

lf_dataplane_test.py: Script updates

---

py-scripts/lf_interop_ping.py

- Added support for configuring devices listed in device_list with SSID,password, and security
- Added support for configuring devices in group with specific profiles
- Added ability to set device-specific or common pass/fail values for all devices
Verified CLI:
python3 lf_interop_ping.py --mgr 192.168.244.97 --real --target 192.168.1.3 --ping_interval 1 --ping_duration 1  --ssid RDT_wpa2 --security wpa2 --passwd OpenWifi --server_ip 192.168.244.97 --wait_time 30

lf_interop_ping.py: Add device configuration and pass/fail validation

---

py-scripts/lf_interop_ping_plotter.py
py-scripts/lf_interop_qos.py
py-scripts/lf_webpage.py
py-scripts/real_application_tests/zoom_automation/lf_interop_zoom.py

This PR adds a couple of the interop scripts that recently saw updates merged to linting checks, fixing necessary flagged code along the way.

Add Interop Scripts to Linting

---

py-scripts/lf_dataplane_test.py

No argument checks or JSON presently.
Verified:
./lf_dataplane_test.py \
--upstream       1.2.AP-ROOT-LAN
--station        1.1.sta1000 \
--attenuator     1.1.3273 \
--atten_min      0 \
--atten_step     10 \
--atten_max      20 \
--attenuator2    1.1.3280 \
--atten2_min     0 \
--atten2_step    20 \
--atten2_max     40

lf_dataplane_test.py: Support simplified attenuator CLI

---

py-json/cv_test_manager.py
py-json/multicast_profile.py
py-json/test_group_profile.py
py-scripts/lf_wifi_capacity_test.py

Mostly linting fixes and commenting/docstrings.

Updates to CV scripts and library code

---

py-json/wifi_monitor_profile.py
py-scripts/lf_sniff_radio.py

Among many small improvements (e.g. logging, readability), this PR fixes linting failure

Updates to `lf_sniff_radio.py`

---

README.md
lanforge_client/README.md
lanforge_client/examples/query_metrics/README.md
py-scripts/README.md
py-scripts/examples/README.md
py-scripts/sandbox/README.md
py-scripts/scripts_deprecated/README.md

More README updates, this time spread across several areas of the repository. The main changes are consolidation into the root README and includes updates to the LANforge HTTP API section with specific examples on querying the API.

More README updates

---

py-scripts/tools/lf_update.py

Note: this script uses scrapli which is not part of LANforge Scripts dependencies.
Help Summary:
This script will perform an update on lanforge of: GUI version,
Kernel version,
then reboot,
run check_large_files.bash
Verified:
./lf_update.py \
--mgr 192.168.50.103 \
--root_user root \
--root_password lanforge \
--user lanforge \
--user_password lanforge \
--mgr_ssh_port 22\
--lfver 5.5.1\
--kver 6.15.6+\
--log_level info

py-scripts/tools/lf_update.py : initial commit

---

cc_module_uci.py

Added reading the cac timer to the cc_module_uci.py 
vscode
"args":[
"--scheme","ssh",
"--dest", "192.168.215.167",
"--port", "22",
"--user", "root",
"--passwd", "hfcl!@ion",
"--prompt", "root@HFCL:~#",
"--series", "NA",
"--band", "5g",
"--module", "cc_module_uci",
"--module_scrapli",
"--timeout", "3",
"--ap", "HFCL",
"--ap_band_slot_5g", "NA",
"--wlan", "NA",
"--wlan_id", "NA",
"--wlan_ssid", "ion_5g",
//"--wlan_ssid", "hfcl_5g",
"--tag_policy", "NA",
"--policy_profile", "NA",
"--pathloss", "59",
"--antenna_gain", "6",
"--lfmgr", "192.168.212.55",
"--upstream_port", "eth1",
"--lfresource", "1",
"--radio", "wiphy0",
"--station", "sta0000",
"--ssid", "ion_5g",
//"--ssid", "hfcl_5g",
"--ssidpw", "12345678",
"--security", "wpa2",
"--bssid", "DEFAULT",
"--no_cleanup_station",
"--channel", …

cc_module_uci.py added cac timer

---

py-scripts/lf_interop_throughput.py

Modified incremental_capacity list based on MAC ID configured devices and Included RTT metrics in the generated report

lf_interop_throughput.py : Updated incremental capacity and add RTT in report

---

py-scripts/tools/lf_update.py

Lf update parse updating the scrapli parsing commands to work for the AT7
The AT7 has a different prompt as compared to the 523c

Lf update parse updating the scrapli parsing commands to work for the AT7

---

py-scripts/lf_ftp.py

- In get_layer4_data(), unified API call for all fields, so we now use data directly from get_layer4_data(). To ensure to have no size constraint issue, removed the redundant API call.
Verfied CLI: python3 lf_ftp.py --file_sizes 10MB --mgr 192.168.242.2 --traffic_duration 1m --directions Download --clients_type Real --ap_name Netgear --bands 2.4G --upstream_port eth1

lf_ftp.py : Removed redundant single-field API call
